title: 'rcm.github.io'
description: "The best in basement journalism."
baseurl:
url: "https://rcm.github.io"

header_pages:
  - index.md

style: dark

footer: 'Support the RCM project on <a href="https://github.com/starb-ck">github</a>.'

# Build settings
markdown: kramdown
remote_theme:  b2a3e8/jekyll-theme-console

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag